name: Build Documents

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./docker.sh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: '*.pdf'

      - name: Release
        uses: ncipollo/release-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          artifacts: "cv.pdf,resume.pdf"
          artifactContentType: 'application/pdf'
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: 'master'
          tag: 'v${{ github.run_number }}'

      - name: Move files
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          mkdir ./public
          mv ./*.pdf ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          enable_jekyll: false
